#version: v2
runtime: python38
instance_class: F2

#automatic_scaling:
#  min_idle_instances: 1
#  max_idle_instances: 100
#  min_pending_latency: automatic
#  max_pending_latency: automatic

handlers:
- url: /.*
  secure: always
  script: auto
