# Generated by Django 2.2.13 on 2022-01-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_planet_blank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('GREEN', 'Green'), ('PURPLE', 'Purple'), ('UNKNOWN', 'Unknown')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('BLONDE', 'Blonde'), ('RED', 'Red'), ('WHITE', 'White'), ('BALD', 'Bald')], max_length=32),
        ),
    ]
