# Generated by Django 2.2.13 on 2022-01-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220131_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('yellow', 'YELLOW'), ('red', 'RED'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('unknown', 'UNKNOWN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('black', 'BLACK'), ('brown', 'BROWN'), ('blond', 'BLONDE'), ('red', 'RED'), ('white', 'WHITE'), ('bald', 'BALD')], max_length=32),
        ),
    ]
